# Generated by Django 5.0.3 on 2026-04-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="客户名称"
                    ),
                ),
                (
                    "business_model",
                    models.CharField(
                        choices=[("Hunting", "Hunting"), ("Farming", "Farming")],
                        db_index=True,
                        max_length=20,
                        verbose_name="业务模式",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="区域"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="城市"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="详细地址")),
                (
                    "description_x",
                    models.TextField(blank=True, verbose_name="客户描述"),
                ),
                (
                    "score_x",
                    models.IntegerField(default=0, verbose_name="客户潜力评分"),
                ),
                (
                    "description_y",
                    models.TextField(blank=True, verbose_name="竞争环境描述"),
                ),
                ("score_y", models.IntegerField(default=0, verbose_name="竞争评分")),
                (
                    "key_person",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="关键联系人"
                    ),
                ),
                ("score_z", models.IntegerField(default=0, verbose_name="关系评分")),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        db_index=True,
                        max_length=1,
                        verbose_name="客户等级",
                    ),
                ),
                (
                    "client_strategy",
                    models.TextField(blank=True, verbose_name="客户策略"),
                ),
                (
                    "potential_contribution",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="年度潜在贡献(KEUR)",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="状态"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "db_table": "customers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client_name"], name="customers_client__a06258_idx"
                    ),
                    models.Index(fields=["level"], name="customers_level_ab679f_idx"),
                    models.Index(
                        fields=["business_model"], name="customers_busines_58a799_idx"
                    ),
                    models.Index(
                        fields=["area", "city"], name="customers_area_173e84_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="职位"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="电话"),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=100, verbose_name="邮箱"),
                ),
                (
                    "is_key_person",
                    models.BooleanField(default=False, verbose_name="是否关键人"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "联系人",
                "verbose_name_plural": "联系人",
                "db_table": "contacts",
                "ordering": ["-is_key_person", "name"],
            },
        ),
    ]
