# Generated by Django 5.0.3 on 2026-04-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        db_index=True,
                        help_text="手动输入或从客户列表选择",
                        max_length=200,
                        verbose_name="客户名称",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="区域"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="地址"),
                ),
                (
                    "tasks",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        verbose_name="任务类型",
                    ),
                ),
                ("definition", models.TextField(verbose_name="项目定义/名称")),
                (
                    "due_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="截止日期"
                    ),
                ),
                (
                    "revise_date",
                    models.DateField(blank=True, null=True, verbose_name="修订日期"),
                ),
                (
                    "finish_date",
                    models.DateField(blank=True, null=True, verbose_name="完成日期"),
                ),
                (
                    "revenue",
                    models.CharField(blank=True, max_length=100, verbose_name="营收"),
                ),
                (
                    "responsibility",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="责任人"
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        default=list,
                        help_text='格式: [{"timestamp": "2026-04-12T10:30:00", "content": "...", "user": "..."}]',
                        verbose_name="行动记录",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weekly_reports",
                        to="customers.customer",
                        verbose_name="关联客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Report",
                "verbose_name_plural": "Weekly Reports",
                "db_table": "weekly_reports",
                "ordering": ["-due_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client_name"], name="weekly_repo_client__ba5db4_idx"
                    ),
                    models.Index(fields=["area"], name="weekly_repo_area_9b5c26_idx"),
                    models.Index(fields=["tasks"], name="weekly_repo_tasks_9e99cf_idx"),
                    models.Index(
                        fields=["responsibility"], name="weekly_repo_respons_412d20_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="weekly_repo_due_dat_220c29_idx"
                    ),
                ],
            },
        ),
    ]
