# Generated by Django 5.0.3 on 2026-04-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_weeklyreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyreport",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "进行中"), ("completed", "已完成")],
                db_index=True,
                default="in_progress",
                max_length=20,
                verbose_name="项目状态",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyreport",
            index=models.Index(fields=["status"], name="weekly_repo_status_5b0092_idx"),
        ),
    ]
