# Generated by Django 5.0.3 on 2026-05-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_weeklyreport_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerRevenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(db_index=True, verbose_name="月份")),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="营收"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_records",
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户营收",
                "verbose_name_plural": "客户营收",
                "db_table": "customer_revenues",
                "ordering": ["-month", "customer__client_name"],
                "indexes": [
                    models.Index(
                        fields=["customer", "month"],
                        name="customer_re_custome_685043_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="customerrevenue",
            constraint=models.UniqueConstraint(
                fields=("customer", "month"), name="unique_customer_month_revenue"
            ),
        ),
    ]
