# Generated by Django 5.0.3 on 2026-05-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customerrevenue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="alias",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, verbose_name="别名"
            ),
        ),
    ]
