# Generated by Django 5.0.3 on 2026-05-27 09:24

from math import ceil

from django.db import migrations, models


def recalculate_existing_customer_levels(apps, schema_editor):
    Customer = apps.get_model("customers", "Customer")
    customers = list(Customer.objects.all())
    ranked_customers = [
        customer
        for customer in customers
        if all((score or 0) != 0 for score in (customer.score_x, customer.score_y, customer.score_z))
    ]
    ranked_customers.sort(
        key=lambda customer: (
            -((customer.score_x or 0) + (customer.score_y or 0) + (customer.score_z or 0)),
            customer.client_name.lower(),
            customer.id,
        )
    )

    ranked_count = len(ranked_customers)
    top_10_cutoff = ceil(ranked_count * 0.10)
    top_25_cutoff = ceil(ranked_count * 0.25)
    top_60_cutoff = ceil(ranked_count * 0.60)
    next_levels = {}
    for position, customer in enumerate(ranked_customers, start=1):
        if position <= top_10_cutoff:
            next_levels[customer.id] = "A"
        elif position <= top_25_cutoff:
            next_levels[customer.id] = "B"
        elif position <= top_60_cutoff:
            next_levels[customer.id] = "C"
        else:
            next_levels[customer.id] = "D"

    changed_customers = []
    for customer in customers:
        next_level = next_levels.get(customer.id, "X")
        if customer.level != next_level:
            customer.level = next_level
            changed_customers.append(customer)

    if changed_customers:
        Customer.objects.bulk_update(changed_customers, ["level"])


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_customer_alias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("X", "X")],
                db_index=True,
                max_length=1,
                verbose_name="客户等级",
            ),
        ),
        migrations.RunPython(recalculate_existing_customer_levels, migrations.RunPython.noop),
    ]
