# Generated by Codex on 2026-07-08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_add_x_customer_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerContactRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contacted_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="联系时间")),
                ("contact_date", models.DateField(db_index=True, editable=False, verbose_name="联系日期")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_records",
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户联系记录",
                "verbose_name_plural": "客户联系记录",
                "db_table": "customer_contact_records",
                "ordering": ["-contacted_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="customercontactrecord",
            constraint=models.UniqueConstraint(fields=("customer", "contact_date"), name="unique_customer_contact_per_day"),
        ),
        migrations.AddIndex(
            model_name="customercontactrecord",
            index=models.Index(fields=["customer", "contact_date"], name="customer_co_custome_0eae11_idx"),
        ),
        migrations.AddIndex(
            model_name="customercontactrecord",
            index=models.Index(fields=["customer", "contacted_at"], name="customer_co_custome_a3b0e0_idx"),
        ),
    ]
